-- MySQL Script generated by MySQL Workbench
-- Wed Jun 30 10:09:18 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `nombreProducto` VARCHAR(30) NOT NULL,
  `fotoProducto` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `cedula` INT NOT NULL,
  `nombre` VARCHAR(25) NOT NULL,
  `apellido` VARCHAR(25) NOT NULL,
  `foto` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cedula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NivelUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NivelUsuario` (
  `idNivelUsuario` INT NOT NULL,
  `nombreNivelUsuario` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idNivelUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `cedula` INT NOT NULL,
  `idNivelUsuario` INT NOT NULL,
  `nombreUsuario` VARCHAR(30) NOT NULL,
  `contUsuario` VARCHAR(15) NOT NULL,
  `fotoUsuario` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Persona1_idx` (`cedula` ASC) VISIBLE,
  INDEX `fk_Usuario_NivelUsuario1_idx` (`idNivelUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Persona1`
    FOREIGN KEY (`cedula`)
    REFERENCES `mydb`.`Persona` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_NivelUsuario1`
    FOREIGN KEY (`idNivelUsuario`)
    REFERENCES `mydb`.`NivelUsuario` (`idNivelUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`InventarioItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`InventarioItem` (
  `idInventarioItem` INT NOT NULL AUTO_INCREMENT,
  `idNivelUsuario` INT NOT NULL,
  PRIMARY KEY (`idInventarioItem`),
  INDEX `fk_catalogoItem_NivelUsuario1_idx` (`idNivelUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_catalogoItem_NivelUsuario1`
    FOREIGN KEY (`idNivelUsuario`)
    REFERENCES `mydb`.`NivelUsuario` (`idNivelUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoriaItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoriaItem` (
  `idcategoriaItem` INT NOT NULL,
  `nombreCategoria` VARCHAR(20) NOT NULL,
  `idInventarioItem` INT NOT NULL,
  PRIMARY KEY (`idcategoriaItem`),
  INDEX `fk_categoriaItem_InventarioItem1_idx` (`idInventarioItem` ASC) VISIBLE,
  CONSTRAINT `fk_categoriaItem_InventarioItem1`
    FOREIGN KEY (`idInventarioItem`)
    REFERENCES `mydb`.`InventarioItem` (`idInventarioItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Item` (
  `codigoItem` INT NOT NULL AUTO_INCREMENT,
  `stock` INT NOT NULL,
  `idProducto` INT NOT NULL,
  `idcategoriaItem` INT NOT NULL,
  PRIMARY KEY (`codigoItem`),
  INDEX `fk_Item_Producto1_idx` (`idProducto` ASC) VISIBLE,
  INDEX `fk_Item_categoriaItem1_idx` (`idcategoriaItem` ASC) VISIBLE,
  CONSTRAINT `fk_Item_Producto1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Item_categoriaItem1`
    FOREIGN KEY (`idcategoriaItem`)
    REFERENCES `mydb`.`categoriaItem` (`idcategoriaItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departamento` (
  `idDepartamento` INT NOT NULL,
  `nombreDep` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idDepartamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `idEmpleado` INT NOT NULL AUTO_INCREMENT,
  `idDepartamento` INT NOT NULL,
  `cedula` INT NOT NULL,
  `idCargo` INT NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `telefono` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`idEmpleado`),
  INDEX `fk_Empleado_Departamento_idx` (`idDepartamento` ASC) VISIBLE,
  INDEX `fk_Empleado_Persona1_idx` (`cedula` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_Departamento`
    FOREIGN KEY (`idDepartamento`)
    REFERENCES `mydb`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_Persona1`
    FOREIGN KEY (`cedula`)
    REFERENCES `mydb`.`Persona` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Asistencia` (
  `idAsistencia` INT NOT NULL AUTO_INCREMENT,
  `idEmpleado` INT NOT NULL,
  `horaEntrada` DATETIME NOT NULL,
  `horaSalida` DATETIME NOT NULL,
  `horasTrabajadas` DATETIME NOT NULL,
  PRIMARY KEY (`idAsistencia`),
  INDEX `fk_Asistencia_Empleado1_idx` (`idEmpleado` ASC) VISIBLE,
  CONSTRAINT `fk_Asistencia_Empleado1`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `mydb`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
